{% set name = "ansi2html" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f124ea7efcf3f24f1f9398e527e688c9ae6eab26b0b84e1299ef7f94d92c596
  patches:
    - 0001-No-python3.exe-on-Windows.patch

build:
  number: 2
  skip: True  # [py<36]
  entry_points:
    - ansi2html=ansi2html.converter:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six

test:
  source_files:
    - tests
  imports:
    - ansi2html
  commands:
    - nosetests tests/test_ansi2html.py
    - ansi2html --help
  requires:
    - mock >=0.8
    - nose

about:
  home: https://pypi.python.org/pypi/ansi2html
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Convert text with ANSI color codes to HTML or to LaTeX.
  description: |
    ansi2html allows users to convert text with ANSI color codes
    to HTML or to Latex.
  doc_url: https://pypi.python.org/pypi/ansi2html/
  doc_source_url: https://github.com/pycontribs/ansi2html/blob/master/README.rst
  dev_url: https://github.com/pycontribs/ansi2html

extra:
  recipe-maintainers:
    - nehaljwani
