# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ehU9MyEOnV27LOi5rmzU1U2PjcWlo0w6FZSQCjMrDg/kdg+L6xhBULzf86UT8K2EFWRl5Y2c8Cv4ocx+7aHcLkv50vY9wVS2yh/KbFQhPZP25fPA+veuVtLZ5ziLvloA7PvqLNI5wUcNi1MSJ3D6EsyCVgxifaQ6VLsmYubPdeDuUevobVIIl0Zmr7W5vmvo4CAyAgtOg0136kDIrJ5dFP/IXiQqte6K6LVuGS5fKAFsu/czf5dAhrsZpJQpcyg72LCaMCim1LFK3CagSivwPCIWSjMw2T76yKkOaM8HSj7ebRphCS9YfeZKF48nFkmFYe/xsPkCwWBQt54Fnj+yrW1hiobTVAgGD8aTRCMrvG4Q7WXs5HXPSOFveA7hULJykccoPA/9AAZixKX+EUudMOP+Kfi+N/5xby27vKZPObg+9jmv/wpblsQXvBMf5C0Bzhwu1p8+OZ96ZmkbZUII/iazS+GXPSWIXLS/BYgIKOKlsfiLrW/7bxXzJgTM3kbMYM5k1TLI76UM2CDF/IshGIA9TuBWbDckrB7bimb9CRMG1D8+DR3Y8DYbJ+l46Svs0NDR9I6s7WAFSSfeeqFNguynSm0GHY4UjqgnfSWRV3HhFpGxCCMoJHrZMKmnd0G2a93I/LG6n20hilAHUpOq1UdBs4fLopG76/gyfXErIUg="

matrix:
  include:
    - env: CONFIG=linux_aarch64_python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python3.11.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python3.8.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python3.9.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.10.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.11.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.8.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.9.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python3.9.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False"; else export IS_PR_BUILD="True"; fi


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi